---
title: "Transmissão de Preço no mercado de combustíveis"
author: "Caio, Lucas e Marcos"
date: "3 de fevereiro de 2017"
output: pdf_document

---


\section{Introdução}

Estudos sobre a interação dos mercados e transmissão de preços são recorrentes na literatura econômica. Os primeiros estudos que se preocuparam com esse assunto analisaram apenas a correlação entre os preços, em cada mercado ou elo da cadeia produtiva, para explicar como se dava essa transmissão. O primeiro modelo que se preocupou com o caráter dinâmico dessas relações foi o proposto por Ravallion (1986), observando a diferença entre a relação de preços de custo prazo, da relação de equilíbrio de preços no longo prazo, como bem aponta Mattos (2009).

Conforme Garaffa (2016), modelos de forma reduzida (ou modelos financeiros) ganharam força ao longo dos anos 2000, devido ao processo de financeirização do mercado de commodities. Estes modelos diferem dos modelos estruturais ao focar na relação de interação entre os preços, não se preocupando com a estimação de parâmetros de oferta ou demanda. Desta forma, modelos na forma reduzida demandam apenas informações sobre as propriedades das séries históricas de preços, e se desenvolveram a partir dos modelos autorregressivos (AR), com posterior incorporação de dos modelos de correção de erro e análises de cointegração. (HUNTINGTON et al., 2013).

Neste trabalho será analisado a interação de preços de combustíveis (Gasolina e Etanol) ao posto e ao consumidor na cidade de Guarulhos-SP, para tal será utilizado método TVEC (_Threshold Vector Errors Correction_), que é uma versão não linear do modelo do vetor de correção de erros (VEC) membro do grupo de modelos TAR, do inglês _Threshold Autoregressive Models_. Os modelos TAR apresentam um avanço em relação aos seus anteriores, lineares, no sentido de possibilitarem a incorporação de assimetrias  e custos de transação  ao arcabouço de estudo da integração de mercados, tais imperfeições geram não linearidades no movimento de adaptação de preços que não são captadas por modelos autorregressivos tradicionais. Vale apontar que esses modelos, apesar de serem compatíveis com o conceito de custos de transação, não são capazes de apontar a origem desses custos, apenas podem mensurar seus efeitos.

São exemplos de trabalhos que adotaram modelos com threshold: Serra e Gil (2006), que tratam os custos de transação no mercado de porco europeu por meio do modelo TAR; Bem-Kaabia e Gil (2007), que também por meio de um modelo TAR analisaram as assimetrias entre os preços ao produtor e varejista no mercado de carne de carneiro espanhol; Nick e Threschler (2014), que observaram a aplicabilidade da lei do preço único no mercado de gás natural europeu por meio de um modelo TVEC; Mattos (2009), que por meio de um modelo TVEC analisou os custos de transação no mercado do boi gordo brasileiro, e em trabalho semelhantes Mattos (2009), com uso de um modelo TAR, analisa a mesma questão no mercado de frango brasileiro; e Garaffa (2016), em consonância com o trabalho de Nick e Theschler (2014) avalia o mercado de gás europeu por meio de modelos TVEC e TVAR.

O objeto de estudo abordado neste trabalho será o mercado de combustíveis de Guarulhos. Podemos dizer que tal escolha se justifica pela importância da questão energética, tanto em âmbito nacional como internacional, e no fato de que Guarulhos, como segunda maior cidade do Estado de São Paulo, pode apresentar bons indícios de como este mercado se comporta em nível metropolitano ou mesmo estadual.

\section{O mercado de Combustível}

\section{Objetivos}

O objetivo principal deste trabalho é analisar a relação de transmissão de preços entre distribuidores e revendedores de combustíveis - especificamente gasolina tipo C - no município de Guarulhos. Para tal, empregou-se a metodologia de Cointegração com \textit{threshold} e testou-se a presença de assimetria na transmissão de preços. Nesse contexto uma pergunta interessante surge: como a entrada de veículos com a tecnologia \textit{flexfuel} pode ter alterado (ou não) a transmissão vertical de preços do mercado análisado? 

\section{Dados}

Estes dados foram disponibilizados pela Superintendência de Planejamento e Pesquisa no sítio da ANP e refletem o preço de venda médio (por litro) de gasolina tipo C realizadas pelas distribuidoras e revendedoras dos derivados combustíveis de petróleo no município de Guarulhos. O período de análise é de janeiro de 2003 à dezembro de 2012, entretanto, a fim de melhorar a precisão da análise e facilitar a comparação dos resultados, este período é dividido em dois subperíodos, em função da influência sofrida pela entrada da tecnologia flex fuel no mercado.

Os valores mensais correntes foram deflacionados utilizando a série histórica do Índice Nacional de Preços ao Consumidor (IPCN), disponibilizada no sitio do Instituto Brasileiro de Geografia e Estatística, IBGE. Foi utilizado o mês de fevereiro de 2016 como referência para os cálculos. O 





\section{Metodologia}


Modelos que examinam a natureza da transmissão vertical de preços foram analisados em diferentes mercados, mas principalmente no setor alimentício. Esta relação começou a ser estudada pelo modelo de Houck(1977) e passou por diversas modificações com o passar do tempo. Seja o modelo estático na forma reduzida dado por:

\begin{equation} \label{rer}
\sum_{\tau=1}^{t} \Delta PR_{\tau}=\alpha_{0} + \alpha_{1}\sum_{\tau=1}^{t}\Delta PPI_{\tau} + \alpha_{2}\sum_{\tau=1}^{t}\Delta PPF_{\tau} + \varepsilon_{t}
\end{equation}


Em que $PR_{\tau}$ representa variações nos preços do revendedor, $PPI_{\tau}$ e $PPF_{\tau}$ são as variações positivas e negativas nos preços de distribuição/produção, respectivamente,$\alpha_{0}$,$alpha_{1}$ e $\alpha{2}$ são coeficientes a serem estimados, $t$ é o tempo corrente e $\varepsilon_{t}$ é o termo de erro aleatório. A hipótese nula de ajuste simétrico de preços é testada por meio das estimativas de $\alpha_{1}$ e $\alpha_{2}$. É comum o uso de técnicas de cointegração para estimas estes parâmetros, entretanto, von Cramon-Taubadel e Loy (1997) demonstraram que a especificação na equação \ref{rer} é inconsistente com o conceito de cointegração. Em seguida, Azzam (1999), em um  trabalho seminal, mostrou que na presença de rigidez de preço o uso de funções não reversíveis, como é o caso da equação \ref{rer}, o teste de assimetria não é apropriado.

Nesse sentido, este trabalho emprega um modelo de cointegração que reconhece o fato de que um choque pode ter que atingir um nível crítico antes que uma resposta significativa seja provocada.Considere a relação simples que é usada como base para várias análises de cointegração:

\begin{equation}
\Delta x_{t}=\pi x_{t-1} + \vartheta_{t}
\end{equation}

Em que $x_{t}$ é um vetor de variáveis estacionárias não aleatórias, $\pi$ é uma matriz nxn e $\vartheta_{t}$ é um componente de erro normalmente distribuido. O procedimento de cointegração de Johansen consiste em estimar $\pi$ e determinar seu rank. A idéia dessa abordagem é testar se o rank de $\pi$ é ou não igual a zero. Em caso negativo, o sistema exibe ajustamento simetrico em torno de $x_{t}=0$, ou seja, para qualquer $x_{t}\neq 0$, $\Delta x_{t+1}$ será igual à $\pi x_{t}$.


A abordagem de dois passos de Engle-Granger (1987) também testa o ajuste simétrico. A abordagem usa OLS para estimar a relação de equilíbrio de longo prazo como:

\begin{equation} \label{wfw}
x_{1t}=\beta_{0}+\beta_{2}x_{2t}+...+\beta_{n}x_{nt}+\mu_{t}
\end{equation}

Em que $x_{it}$ são variáveis não estacionárias, $\beta_{i}$ são parãmetros a serem estimados e $\mu_{t}$ é um termo de erro que pode ser serialmente correlacionados. O resíduos são utilizados para estimar a seguinte relação:

\begin{equation} \label{acf}
\Delta \mu_{t}=\rho \mu_{t-1}+\varepsilon_{t}
\end{equation}

Em que $\varepsilon_{t}$ é um ruído branco. A rejeição da hipótese nula de não cointegração (isto é, aceitando a hipótese alternativa de $2<\rho <0$) implica que os resíduos na Equação 3 são estacionários com média zero. De acordo com o teorema de Engle-Granger (1987), se $\rho \neq 0$, \ref{wfw} e \ref{acf} implicam na existencia de um modelo de correção de erros que pode ser representado por:

\begin{equation} \label{deo}
\Delta x_{1t}=\delta_{j}\left ( x_{1t-1}-\beta_{0}-\beta_{2t-1}-...-\beta_{n}x_{nt-1} \right ) + \sum_{j=1}^{k}\beta_{2j}\Delta x_{2,t-j}+...+\sum_{j=1}^{k}\beta_{nj}\Delta x_{n,t-j}+\upsilon_{1t}
\end{equation}

Em que $k$ determina a defasagem e $\upsilon_{1t}$ é um ruído branco. O termo dentro dos parênteses fornece o mecanismo de correção de erro. Enders e Granger (1998) argumentam que os testes de cointegração de Engle-Granger e Johansen são mal especificados se o ajuste é assimétrico. Quando esses testes são empregados para analisar a transmissão de preço de uma relação vertical de um mercado, a hipótese implicita é que as respostas as variações de preços são simétricas: choques no preço de produção/distribuição geram variações da mesma magnitude no preço dos revendedores, independente do choque ser positivo ou negativo.

Enders e Granger (1998) consideram um modelo alternativo de correção de erro denominado modelo autorregressivo com \textit{threshold} (TAR), no qual a Equação \ref{acf} é representada como:

\begin{equation}
\Delta \mu_{t}=\left\{\begin{matrix}
\rho_{1}\mu_{t-1}+\varepsilon_{t} \ \ \ \text{if} \ \ \ \mu_{t-1}\geq 0 \\ 
\rho_{2}\mu_{t-1}+\varepsilon_{t} \ \ \ \text{if} \ \ \ \mu_{t-1}<  0
\end{matrix}\right.
\end{equation}

A condição necessária para $\left \{ \mu_{t} \right \}$ ser estacionária é $-2<(\rho_{1},\rho{2})<0$. Enders e Granger (1998) mostram que Se a seqüência é estacionária, as estimativas por mínimos quadrados de $\rho_ {1}$ e $\rho_ {2}$ têm uma distribuição normal assintótica multivariada. O processo de ajuste é então formalmente quantificado como por meio da função indicadora:

\begin{equation} \label{des}
\Delta \mu_{t}=I_{t}\rho_{1}\mu_{t-1} +\left ( 1-I_{t} \right )\rho_{2}\mu_{t-1}+\varepsilon_{t}
\end{equation}

Tal que:
\begin{equation} \label{fei}
I_{t}=\left\{\begin{matrix}
1 \ \ \ \text{if} \ \ \ \mu_{t-1}\geq 0 \\ 
0 \ \ \ \text{if} \ \ \ \mu_{t-1}<  0
\end{matrix}\right.
\end{equation}


Nesse caso, zero representa o valor do \textit{threshlod}. Modelos que utilizam as equações \ref{des} e \ref{fei} são referidos como modelos de auto-regressão com \textit{threshold} (TAR), enquanto o teste para comportamento de equilibrio de longo prazo com \textit{threshold} é denominado teste de cointegração com \textit{threshold}. Assumindo que o sistema é convergente, $\mu_{t}=0$ éconsiderado o valor de equilibrio de longo prazo da série. Se $\mu_{t}$ está abaixo do valor de equilibrio, o ajustamento é de $\rho_{1}\mu_{t}$, por outro lado, Se $\mu_{t}$ está acima do valor de equilibrio, o ajustamento é de $\rho_{2}\mu_{t}$ 

Dado que o ajuste é simétrico ou seja, $\rho_{1}=\rho_{2}$, a abordagem de Engle-Granger é um caso especial das Equações \ref{des} e \ref{fei}.Dada a existência de um vetor de cointegração, a representação do modelo de correção de erro apresentada em \ref{deo} pode ser escrita como:

\begin{equation} 
\Delta x_{1t}=\rho_{1.1}I_{t}\mu_{t-1}+\rho{2.1}(1-I_{t})\mu_{t-1}+\sum_{j=1}^{k}\beta_{2j}\Delta x_{2,t-j}+...+\sum_{j=1}^{k}\beta_{nj}\Delta x_{n,t-j}+\upsilon_{1t}
\end{equation}

Em que $\rho_{1.1}$ e $\rho_{2.1}$ são os coeficientes de ajustamento para diferenças positivas e negativas, respectivamente. Enders e Granger (1998) mostraram que a equação \ref{des} pode ser extendido para um modelo de defasagens em diferenças, como:

\begin{equation} \label{fea}
\Delta \mu_{t}=I_{t}\rho_{1}\mu_{t-1} +\left ( 1-I_{t} \right )\rho_{2}\mu_{t-1}+\sum_{i=1}^{\rho-1}\gamma_{i}\delta \mu_{t-i} +\varepsilon_{t}
\end{equation}

Em vez de estimar a equação \ref{des} por meio da função indicadora \ref{fei}, o \textit{threshold} pode ser determinado pela variação de $\mu_{t}$. Nesse caso, a função indicador fica:

\begin{equation} \label{odi}
I_{t}=\left\{\begin{matrix}
1 \ \ \ \text{if} \ \ \ \Delta\mu_{t-1}\geq 0 \\ 
0 \ \ \ \text{if} \ \ \ \Delta\mu_{t-1}<  0
\end{matrix}\right.
\end{equation}


De acordo com Enders e Granger (1998), a substituição de \ref{fei} por \ref{odi} é especialmente valiosa quando o ajuste é assimétrico, de modo que a série exibe mais "momentos" em uma direção do que em outras. Modelos estimados usando as Equações 3, \ref{res} e \ref{odi} são denominados modelos autorregressivos \textit{momentum-threshold} (M-TAR).

No modelo TAR, se, por exemplo, $-2<\rho_{1}<\rho_{2}<0$ a fase negativa da sequênica $\{\mu_{t} \}$ deverá ser mais persistente que a fase positiva. Enquanto no modelo M-TAR, se, por exemplo $|\rho_{1}|<|\rho_{2}|$, então o modelo apresenta menos variações positivas que negativas para $\Delta \mu_{t-1}$

As estatísticas de teste para a hipótese nula $(\rho_{1}=\rho_{2}=0)$ usando a especificação TAR e M-TAR  são chamadas $\Phi_{\mu}$ e $\Phi_{\mu}^{*}$, respectivamente. Três fatores principais determinam as distribuições de $\Phi_{\mu}$ e $\Phi_{\mu}^{*}$. Estes incluem o número de defasagens de $\mu_{t}$ na Equação \ref{fea}, o número de variáveis e o tipo de elementos determinísticos incluídos na relação de cointegração. Os valores críticos apropriados para $\Phi_{\mu}$ e $\Phi_{\mu}^{*}$ são apresentados em Enders e Siklos (1998) e Enders e Granger (1998).



\section{Resultados}

A hipótese de que as séries de preços analisadas são não estacionárias, é testada pelo método Dickey-Fuller aumentado (ADF). O AIC foi utilizado para determinar a defasagem apropriada das séries. Encontrou-se que uma defasagem é a mais apropriada para amabas as variáveis em análise. Os valores da estatística do teste para os preços de revenda são $-2,92$ e $-6,93$ para e série em nível e em primeira diferença, respectivamente, enquanto a estatística do teste para os preços de distribuição são $-3,01$ e $-8,05$ para e série em nível e em primeira diferença, respectivamente, O valor crítico de $-3,99$ a 1\% de significância sugere que as duas séries tornam-se estacionárias após a primeira diferença.

Para assegurar que a série em primeira diferença é estacionária foi realizado, também, o teste DF-GLS.
O teste DF-GLS (Elliot et al., 1996) é uma versão atualizada do teste ADF padrão (Dickey e Fuller 1979) para quando os dados apresentam média desconhecida e tendência.\footnote{Os autores mostraram, por meio de um \textit{Monte Carlo}, que o DF-GLS tem maior poder e performance em pequenas amostras.} Os resultados foram ao encontro do teste ADF indicando que todas as séries são integradas de primeira ordem.  O teste DG-GLS, por ter mais poder que o teste ADF, fornece um argumento mais forte para a estacionaridade da primeira diferença. A regressão de cointegração é especificada como:

\begin{equation} \label{rre}
PR_{t}=\beta_{0}+\beta_{1}PD_{t}+\mu_{t} 
\end{equation}


Em que $PR_{t}$ é o preço de revenda, $PD_{t}$ representa o preço de distribuição e $\mu_{t}$ os resíduos que, caso sejam estacionários, garantem a relação de longo prazo entre os preços  .Para a análise de cointegração \textit{à la} Engle-Granger (1987), a equação \ref{rre} foi estimada por MQO. A estimativa da relação de equilibrio de longo prazo (com as estatísticas do teste t em parênteses) é dada por:


\begin{equation} \label{rrt}
PR_{t} = \underset{-3.276}{-0.164} + \underset{54.829}{1.216}PD_{t} + \widehat{\mu}_{t}
\end{equation}



Seguindo o procedimento de Engle Granger, os resíduos da Equação \ref{rrt} são usados para estimar:

\begin{equation} \label{res}
\Delta\widehat{\mu}_{t}=\rho_{1}\widehat{\mu}_{t-1}+\gamma_{1}\Delta\widehat{\mu}_{t-1}+ \varepsilon_{t} 
\end{equation}

Como reportado na tabela $www$, o valor estimado de $\rho_{1}$ é de $-0.239$ e a estatística t para a hipótese nula, $\rho_{1}$=0, é de $-4.116$ os valores críticos para o procesimento de Engle-Granger são  $-1.62$, $-1.95$,  $-2.58$ para 10\%, 5\% e 1\%, respectivamente. Portanto, procedimento de Engle-Granger sugere que as duas séries de preços são cointegradas. O p-valor do teste Ljung box também foi reportado na tabela $www$ e indica que os resíduos da equação \ref{res} são não autocorrelacionados.  

Tanto o modelo TAR quanto o MTAR podem ser formulados para diferentes especificações de defasagem. A escolha de uma defasagem em ambos os casos foi feita pelo critério de informação AIC como pode ser obervado pela tabela $ttt$. O modelo de cointegração com \textit{threshold} proporcinou uma estatística $\Phi_\mu$ de $8.398$ e $8.584$  no modelo TAR e MTAR, respectivamente. Portanto, a hipótese nula de $\rho_{1}=\rho_{2}=0$ pode ser rejeitada à um nível de significância de 1\%, o que indica que as séries são cointegradas. Sendo assim, a hipótese nula de ajustamento assimétrico de preços $(\rho_{1}=\rho_{2})$ pode ser testado por meio de um teste F padrão (Enders and
Granger, 1998). A estatística F de $0.002$ no modelo TAR e de $0.326$ no modelo MTAR indicam que não se pode rejeitar a hipótese nula de ajustameto simétrico dos preços. 

Enders e Granger (1998) mostram que em um modelo TAR, como 6 e 7, se $-2<\rho_{1}<\rho_{2}<0$, a série $\mu_{t}$ vai apresentar mais persistencia sempre que $\mu_{t-1}<0$. Sendo esse o resultado obtido tanto no modelo TAR quanto no MTAR, o método de Chan (1993) foi, portanto, empregado para determinar uma estimativa consistente do \textit{threshold}. O valor de $0.03$ foi obtido no modelo TAR e $-0.017$ modelo no modelo MTAR. Aa estimativas dos modelos consistentes não variram muito, mas o modelo MTAR consistente, C.MTAR, sugere que é possível rejeitar a hipótese nula de ajustamento simétrico de preços à $5\%$ de significância. Vale ressaltar que, pelos critério de informação AIC e BIC, o C.MTAR apresentou o melhor ajustamento aos dados.  Os resultados dos quatro modelo podem sem observados pela tabela $fff$.


A possibilidade de um ajuste asSimétrico de preços encontrado pelo modelo c.MTAR implica que é incorreto examinar a dinâmica de curto prazo com um modelo simétrico de correção de erros. Um modelo simétrico de correção de erros não revelaria ajustes diferenciais das mudanças positivas e negativas (Enders e Granger, 1998). Assim, o modelo de correção de erro assimétrico (modelo C.MTAR) são empregados na análise. Eles podem ser representados como:

\begin{equation}
\Delta PR_{t}=\sum_{s=1}^{k}\alpha_{s}\Delta PR_{t-s}+\sum_{s=0}^{k}\beta_{s}\Delta  PD_{t-s}+\gamma_{1}Z_{t-1}^{pos}+\gamma_{2}Z_{t-1}^{neg}
\end{equation}

Em que $k$ é a defasagem, $Z_{t-1}^{pos}$ e $Z_{t-1}^{neg}$ São os termos de correção de erro das regressões da cointegração com \textit{threshold}, representando ajustes de choques positivos e negativos às variações na margem de comercialização. Eles podem ser representados como:

\begin{align*}
Z_{t-1}^{pos}&=I_{t}\left (PR_{t-1}+0.164-1.216PD_{t-1} \right )\nonumber \\
Z_{t-1}^{neg}&=\left (1-I_{t}\right )\left (PR_{t-1}+0.164-1.216PD_{t-1} \right ) \nonumber
\end{align*}

Em que $I$ é uma função indicadora. A tabela $qqq$ apresenta os resultados do modelo de correção de erros. As estimativas do modelo simétrico e assimétrico foram apresentadas para a comparação. Vale ressaltar que as estatísticas t para $Z_{t-1}^{neg}$ e $Z_{t-1}^{pos}$ sugerem que o preço de revenda não responde a choques negativou ou positivos na margem de comercialização (modelo assimétrico).

Para avaliar o efeito da entrada dos carros \textit{flexfuel} no contexto da transmissão de preços de gasolina entre revendedora e distribuidora vamos repetir as duas análises - cointegração com \textit{threshold} e modelo de correção de erro assimétrico para modelo C.MTAR - em dois períodos distintos: de janeiro de 2003 à dezembro de 2007 e de janeiro de 2008 à dezembro de 2012.

Em ambos os períodos, os resultados  sugerem que é possível rejeitar a hipótese nula de não cointegração $(\rho_{1}=\rho_{2}=0)$ à $1\%$. A hipótese nula de ajustamento assimétrico de preços $(\rho_{1}=\rho_{2})$ também foi testada. No período em que haviam menos veiculos \textit{flexfuel} no mercado, de 2003 a 2007, a estatística F encontrada foi de $5.496$, ou seja, pode-se rejeitar a hipótese nula de ajustamento simétrico de preços à $5\%$ de significância. No periódo seguinte, a estatistica F calculada subiu para $7.203$, sendo assim, a hipótese nula pode ser rejeitada à $1\%$. Assim como no período completo, em nenhum dos subperídos o preço de revenda parece responder a choques positivos ou negativos na margem de comercialização.  


\section{Conclusão}






```{r}
# 1. Data preparation
library(zoo)
library(tseries)
library(fUnitRoots)
library(apt)
library(urca)
library(copula)
library(car)
library(xts)



load("C:/Users/Caio/Documents/AdeTrabalho/price/Curitiba/precos.RData")

SP <- precos[grep("CURITIBA", precos$MUNICIPIO), ]

GSP <- SP[grep("GASOLINA COMUM", SP$PRODUTO), ]
#View(GSP)


PDISTGSP<-ts(GSP$PRECOMEDIODISTRIBUICAO,frequency=12,start=c(2003,1),end=c(2012,12))
head(PDISTGSP)

PREVGSP<-ts(GSP$PRECOMEDIOREVENDA,frequency=12,start=c(2003,1),end=c(2012,12))
head(PREVGSP)

INPC <- (ts(GSP$INPCFEV2016100, frequency=12,start=c(2003,1),end=c(2012,12)))
head(INPC)

PREVGSP <- PREVGSP*100
head(PREVGSP)
PREVGSP <- PREVGSP/INPC  
head(PREVGSP)


PDISTGSP <- PDISTGSP*100
head(PDISTGSP)
PDISTGSP <- PDISTGSP/INPC  
head(PDISTGSP)


#2. Stationarity tests
precoadfGREV=ur.df(PREVGSP,type= "trend", selectlags= "AIC")
precoglsGREV=ur.ers(PREVGSP, type = "DF-GLS", model = "trend",lag.max = 1)
precoadfGREV@lags
precoadfGREV@teststat[1]
precoadfGREV@cval[1,]
precoglsGREV@teststat[1]
precoglsGREV@cval[1,]


precoadfGDIST=ur.df(PDISTGSP,type= "trend", selectlags= "AIC")
precoglsGDIST=ur.ers(PDISTGSP, type = "DF-GLS", model = "trend",lag.max = 1)
precoadfGDIST@lags
precoadfGDIST@teststat[1]
precoadfGDIST@cval[1,]
precoglsGDIST@teststat[1]
precoglsGDIST@cval[1,]

diffPREVGSP <- diff(PREVGSP, lag = 1, differences = 1)
diffPDISTGSP <- diff(PDISTGSP, lag = 1, differences = 1)


diffprecoadfGREV=ur.df(diffPREVGSP,type= "trend", selectlags= "AIC")
diffprecoglsGREV=ur.ers(diffPREVGSP, type = "DF-GLS", model = "trend",lag.max = 1)
diffprecoadfGREV@lags
diffprecoadfGREV@teststat[1]
diffprecoadfGREV@cval[1,]
diffprecoglsGREV@teststat[1]
diffprecoglsGREV@cval[1,]


diffprecoadfGDIST=ur.df(diffPDISTGSP,type= "trend", selectlags= "AIC")
diffprecoglsGDIST=ur.ers(diffPDISTGSP, type = "DF-GLS", model = "trend",lag.max = 1)
diffprecoadfGDIST@lags
diffprecoadfGDIST@teststat[1]
diffprecoadfGDIST@cval[1,]
diffprecoglsGDIST@teststat[1]
diffprecoglsGDIST@cval[1,]


# 2. EG cointegration

LR <- lm(PREVGSP ~ PDISTGSP); summary(LR)
(LR.coef <- round(summary(LR)$coefficients, 6))
(ry <- ts(residuals(LR), start=start(PDISTGSP), end=end(PDISTGSP), frequency =12))

summary(eg <- ur.df(ry, type=c("none"), selectlags = c("AIC"))); plot(eg);eg


(eg4 <- Box.test(eg@res, lag = 4, type="Ljung") )
(eg8 <- Box.test(eg@res, lag = 8, type="Ljung") )
(eg12 <- Box.test(eg@res, lag = 12, type="Ljung"))
(eg16 <- Box.test(eg@res, lag = 16, type="Ljung") )
(eg20 <- Box.test(eg@res, lag = 20, type="Ljung"))



# 3. TAR + Cointegration
# best threshold

t3<-ciTarThd(PREVGSP, PDISTGSP, model="tar", lag=0)
(th.tar <- t3$basic); plot(t3)
ttt<-t3$th.final
for (i in 1:12) { # 20 seconds
t3a <- ciTarThd(PREVGSP, PDISTGSP, model="tar", lag=i)
th.tar[i+2] <- t3a$basic[,2]
}
th.tar

t4 <- ciTarThd(PREVGSP, PDISTGSP, model="mtar", lag=0); (th.mtar <- t4$basic)
plot(t4)
mttt<-t4$th.final
for (i in 1:12) {
t4a <- ciTarThd(PREVGSP,PDISTGSP, model="mtar", lag=i)
th.mtar[i+2] <- t4a$basic[,2]
}
th.mtar

t.tar <- ttt; t.mtar <- mttt
#t.tar <- -8.041; t.mtar <- -0.451 # lag = 0 to 4
#t.tar <- -8.701 ; t.mtar <- -0.451 # lag = 5 to 12

mx <- 12
(g1 <-ciTarLag(y=PREVGSP, x=PDISTGSP, model="tar", maxlag=mx, thresh= 0)); plot(g1)
(g2 <-ciTarLag(y=PREVGSP, x=PDISTGSP, model="mtar",maxlag=mx, thresh= 0)); plot(g2)
(g3 <-ciTarLag(y=PREVGSP, x=PDISTGSP, model="tar", maxlag=mx, thresh=t.tar)); plot(g3)
(g4 <-ciTarLag(y=PREVGSP, x=PDISTGSP, model="mtar",maxlag=mx, thresh=t.mtar)); plot(g4)


vv <- 0
(f1 <- ciTarFit(y=PREVGSP, x=PDISTGSP, model="tar", lag=vv, thresh=0 ))
(f2 <- ciTarFit(y=PREVGSP, x=PDISTGSP, model="tar", lag=vv, thresh=t.tar ))
(f3 <- ciTarFit(y=PREVGSP, x=PDISTGSP, model="mtar", lag=vv, thresh=0 ))
(f4 <- ciTarFit(y=PREVGSP, x=PDISTGSP, model="mtar", lag=vv, thresh=t.mtar))

r0 <- cbind(summary(f1)$dia, summary(f2)$dia, summary(f3)$dia,
summary(f4)$dia)
diag <- r0[c(1:4, 6:7, 12:14, 8, 9, 11), c(1,2,4,6,8)]
rownames(diag) <- 1:nrow(diag); diag
e1 <- summary(f1)$out; e2 <- summary(f2)$out
e3 <- summary(f3)$out; e4 <- summary(f4)$out; rbind(e1, e2, e3, e4)

ee <- list(e1, e2, e3, e4); vect <- NULL
for (i in 1:4) {
ef <- data.frame(ee[i])
vect2 <- c(paste(ef[3, "estimate"], ef[3, "sign"], sep=""),
paste("(", ef[3, "t.value"], ")", sep=""),
paste(ef[4, "estimate"], ef[4, "sign"], sep=""),
paste("(", ef[4, "t.value"], ")", sep=""))
vect <- cbind(vect, vect2)
}
item <- c("pos.coeff","pos.t.value", "neg.coeff","neg.t.value")
ve <- data.frame(cbind(item, vect)); colnames(ve) <- colnames(diag)
( res.CI <- rbind(diag, ve)[c(1:2, 13:16, 3:12), ] )
rownames(res.CI) <- 1:nrow(res.CI)




(sem <- ecmSymFit(y=PREVGSP, x=PDISTGSP, lag=1)); names(sem)
(ediaa <- ecmDiag(sem, 3))

aem <- ecmAsyFit(y=PREVGSP, x=PDISTGSP,lag=1, model="mtar", split=FALSE, thresh=t.mtar)
aem
(ccc <- summary(aem))

(edia <- ecmDiag(aem, 3))
(tes <- ecmAsyTest(aem)$out)


aemm <- ecmAsyFit(y=PREVGSP, x=PDISTGSP,lag=1, model="tar", split=FALSE, thresh=t.tar)
aemm
(ccc <- summary(aemm))


(edia <- ecmDiag(aemm, 3))
(tes <- ecmAsyTest(aemm)$out)



###################################2003-2007########################



load("C:/Users/Caio/Documents/AdeTrabalho/price/Curitiba/precos1.RData")

SP <- precos1[grep("CURITIBA", precos1$MUNICIPIO), ]

GSP <- SP[grep("GASOLINA COMUM", SP$PRODUTO), ]
View(GSP)



PDISTGSP<-ts(GSP$PRECOMEDIODISTRIBUICAO,frequency=12,start=c(2003,1),end=c(2007,12))
head(PDISTGSP)

PREVGSP<-ts(GSP$PRECOMEDIOREVENDA,frequency=12,start=c(2003,1),end=c(2007,12))
head(PREVGSP)

INPC <- (ts(GSP$INPCFEV2016100, frequency=12,start=c(2003,1),end=c(2007,12)))
head(INPC)

PREVGSP <- PREVGSP*100
head(PREVGSP)
PREVGSP <- PREVGSP/INPC  
head(PREVGSP)


PDISTGSP <- PDISTGSP*100
head(PDISTGSP)
PDISTGSP <- PDISTGSP/INPC  
head(PDISTGSP)



#2. Stationarity tests
precoadfGREV=ur.df(PREVGSP,type= "trend", selectlags= "AIC")
precoglsGREV=ur.ers(PREVGSP, type = "DF-GLS", model = "trend",lag.max = 1)
precoadfGREV@lags
precoadfGREV@teststat[1]
precoadfGREV@cval[1,]
precoglsGREV@teststat[1]
precoglsGREV@cval[1,]


precoadfGDIST=ur.df(PDISTGSP,type= "trend", selectlags= "AIC")
precoglsGDIST=ur.ers(PDISTGSP, type = "DF-GLS", model = "trend",lag.max = 1)
precoadfGDIST@lags
precoadfGDIST@teststat[1]
precoadfGDIST@cval[1,]
precoglsGDIST@teststat[1]
precoglsGDIST@cval[1,]

diffPREVGSP <- diff(PREVGSP, lag = 1, differences = 1)
diffPDISTGSP <- diff(PDISTGSP, lag = 1, differences = 1)


diffprecoadfGREV=ur.df(diffPREVGSP,type= "trend", selectlags= "AIC")
diffprecoglsGREV=ur.ers(diffPREVGSP, type = "DF-GLS", model = "trend",lag.max = 1)
diffprecoadfGREV@lags
diffprecoadfGREV@teststat[1]
diffprecoadfGREV@cval[1,]
diffprecoglsGREV@teststat[1]
diffprecoglsGREV@cval[1,]


diffprecoadfGDIST=ur.df(diffPDISTGSP,type= "trend", selectlags= "AIC")
diffprecoglsGDIST=ur.ers(diffPDISTGSP, type = "DF-GLS", model = "trend",lag.max = 1)
diffprecoadfGDIST@lags
diffprecoadfGDIST@teststat[1]
diffprecoadfGDIST@cval[1,]
diffprecoglsGDIST@teststat[1]
diffprecoglsGDIST@cval[1,]


# 2. EG cointegration

LR <- lm(PREVGSP ~ PDISTGSP); summary(LR)
(LR.coef <- round(summary(LR)$coefficients, 6))
(ry <- ts(residuals(LR), start=start(PDISTGSP), end=end(PDISTGSP), frequency =12))

summary(eg <- ur.df(ry, type=c("none"), lags=1)); plot(eg)

(eg4 <- Box.test(eg@res, lag = 4, type="Ljung") )
(eg8 <- Box.test(eg@res, lag = 8, type="Ljung") )
(eg12 <- Box.test(eg@res, lag = 12, type="Ljung"))
(eg16 <- Box.test(eg@res, lag = 16, type="Ljung") )
(eg20 <- Box.test(eg@res, lag = 20, type="Ljung"))



# 3. TAR + Cointegration
# best threshold

t3<-ciTarThd(PREVGSP, PDISTGSP, model="tar", lag=0)
(th.tar <- t3$basic); plot(t3)
ttt<-t3$th.final
for (i in 1:12) { # 20 seconds
t3a <- ciTarThd(PREVGSP, PDISTGSP, model="tar", lag=i)
th.tar[i+2] <- t3a$basic[,2]
}
th.tar

t4 <- ciTarThd(PREVGSP, PDISTGSP, model="mtar", lag=0); (th.mtar <- t4$basic)
plot(t4)
mttt<-t4$th.final
for (i in 1:12) {
t4a <- ciTarThd(PREVGSP,PDISTGSP, model="mtar", lag=i)
th.mtar[i+2] <- t4a$basic[,2]
}
th.mtar

t.tar <- ttt; t.mtar <- mttt
#t.tar <- -8.041; t.mtar <- -0.451 # lag = 0 to 4
#t.tar <- -8.701 ; t.mtar <- -0.451 # lag = 5 to 12

mx <- 12
(g1 <-ciTarLag(y=PREVGSP, x=PDISTGSP, model="tar", maxlag=mx, thresh= 0)); plot(g1)
(g2 <-ciTarLag(y=PREVGSP, x=PDISTGSP, model="mtar",maxlag=mx, thresh= 0)); plot(g2)
(g3 <-ciTarLag(y=PREVGSP, x=PDISTGSP, model="tar", maxlag=mx, thresh=t.tar)); plot(g3)
(g4 <-ciTarLag(y=PREVGSP, x=PDISTGSP, model="mtar",maxlag=mx, thresh=t.mtar)); plot(g4)


vv <- 0
(f1 <- ciTarFit(y=PREVGSP, x=PDISTGSP, model="tar", lag=vv, thresh=0 ))
(f2 <- ciTarFit(y=PREVGSP, x=PDISTGSP, model="tar", lag=vv, thresh=t.tar ))
(f3 <- ciTarFit(y=PREVGSP, x=PDISTGSP, model="mtar", lag=vv, thresh=0 ))
(f4 <- ciTarFit(y=PREVGSP, x=PDISTGSP, model="mtar", lag=vv, thresh=t.mtar))

r0 <- cbind(summary(f1)$dia, summary(f2)$dia, summary(f3)$dia,
summary(f4)$dia)
diag <- r0[c(1:4, 6:7, 12:14, 8, 9, 11), c(1,2,4,6,8)]
rownames(diag) <- 1:nrow(diag); diag
e1 <- summary(f1)$out; e2 <- summary(f2)$out
e3 <- summary(f3)$out; e4 <- summary(f4)$out; rbind(e1, e2, e3, e4)

ee <- list(e1, e2, e3, e4); vect <- NULL
for (i in 1:4) {
ef <- data.frame(ee[i])
vect2 <- c(paste(ef[3, "estimate"], ef[3, "sign"], sep=""),
paste("(", ef[3, "t.value"], ")", sep=""),
paste(ef[4, "estimate"], ef[4, "sign"], sep=""),
paste("(", ef[4, "t.value"], ")", sep=""))
vect <- cbind(vect, vect2)
}
item <- c("pos.coeff","pos.t.value", "neg.coeff","neg.t.value")
ve <- data.frame(cbind(item, vect)); colnames(ve) <- colnames(diag)
( res.CI <- rbind(diag, ve)[c(1:2, 13:16, 3:12), ] )
rownames(res.CI) <- 1:nrow(res.CI)


(sem <- ecmSymFit(y=PREVGSP, x=PDISTGSP, lag=1)); names(sem)
(ediaa <- ecmDiag(sem, 3))

aem <- ecmAsyFit(y=PREVGSP, x=PDISTGSP,lag=1, model="mtar", split=FALSE, thresh=t.mtar)
aem
(ccc <- summary(aem))


(edia <- ecmDiag(aem, 3))
(tes <- ecmAsyTest(aem)$out)

aemm <- ecmAsyFit(y=PREVGSP, x=PDISTGSP,lag=1, model="tar", split=FALSE, thresh=t.tar)
aemm
(ccc <- summary(aemm))


(edia <- ecmDiag(aemm, 3))
(tes <- ecmAsyTest(aemm)$out)



###################################2008-2012########################


load("C:/Users/Caio/Documents/AdeTrabalho/price/Curitiba/precos2.RData")

SP <- precos2[grep("CURITIBA", precos2$MUNICIPIO), ]

GSP <- SP[grep("GASOLINA COMUM", SP$PRODUTO), ]
View(GSP)



PDISTGSP<-ts(GSP$PRECOMEDIODISTRIBUICAO,frequency=12,start=c(2008,1),end=c(2012,12))
head(PDISTGSP)

PREVGSP<-ts(GSP$PRECOMEDIOREVENDA,frequency=12,start=c(2008,1),end=c(2012,12))
head(PREVGSP)

INPC <- (ts(GSP$INPCFEV2016100, frequency=12,start=c(2008,1),end=c(2012,12)))
head(INPC)

PREVGSP <- PREVGSP*100
head(PREVGSP)
PREVGSP <- PREVGSP/INPC  
head(PREVGSP)


PDISTGSP <- PDISTGSP*100
head(PDISTGSP)
PDISTGSP <- PDISTGSP/INPC  
head(PDISTGSP)



#2. Stationarity tests
precoadfGREV=ur.df(PREVGSP,type= "trend", selectlags= "AIC")
precoglsGREV=ur.ers(PREVGSP, type = "DF-GLS", model = "trend",lag.max = 1)
precoadfGREV@lags
precoadfGREV@teststat[1]
precoadfGREV@cval[1,]
precoglsGREV@teststat[1]
precoglsGREV@cval[1,]


precoadfGDIST=ur.df(PDISTGSP,type= "trend", selectlags= "AIC")
precoglsGDIST=ur.ers(PDISTGSP, type = "DF-GLS", model = "trend",lag.max = 1)
precoadfGDIST@lags
precoadfGDIST@teststat[1]
precoadfGDIST@cval[1,]
precoglsGDIST@teststat[1]
precoglsGDIST@cval[1,]

diffPREVGSP <- diff(PREVGSP, lag = 1, differences = 1)
diffPDISTGSP <- diff(PDISTGSP, lag = 1, differences = 1)


diffprecoadfGREV=ur.df(diffPREVGSP,type= "trend", selectlags= "AIC")
diffprecoglsGREV=ur.ers(diffPREVGSP, type = "DF-GLS", model = "trend",lag.max = 1)
diffprecoadfGREV@lags
diffprecoadfGREV@teststat[1]
diffprecoadfGREV@cval[1,]
diffprecoglsGREV@teststat[1]
diffprecoglsGREV@cval[1,]


diffprecoadfGDIST=ur.df(diffPDISTGSP,type= "trend", selectlags= "AIC")
diffprecoglsGDIST=ur.ers(diffPDISTGSP, type = "DF-GLS", model = "trend",lag.max = 1)
diffprecoadfGDIST@lags
diffprecoadfGDIST@teststat[1]
diffprecoadfGDIST@cval[1,]
diffprecoglsGDIST@teststat[1]
diffprecoglsGDIST@cval[1,]


# 2. EG cointegration

LR <- lm(PREVGSP ~ PDISTGSP); summary(LR)
(LR.coef <- round(summary(LR)$coefficients, 6))
(ry <- ts(residuals(LR), start=start(PDISTGSP), end=end(PDISTGSP), frequency =12))

summary(eg <- ur.df(ry, type=c("none"), lags=1)); plot(eg)

(eg4 <- Box.test(eg@res, lag = 4, type="Ljung") )
(eg8 <- Box.test(eg@res, lag = 8, type="Ljung") )
(eg12 <- Box.test(eg@res, lag = 12, type="Ljung"))
(eg16 <- Box.test(eg@res, lag = 16, type="Ljung") )
(eg20 <- Box.test(eg@res, lag = 20, type="Ljung"))



# 3. TAR + Cointegration
# best threshold

t3<-ciTarThd(PREVGSP, PDISTGSP, model="tar", lag=0)
(th.tar <- t3$basic); plot(t3)
ttt<-t3$th.final
for (i in 1:12) { # 20 seconds
t3a <- ciTarThd(PREVGSP, PDISTGSP, model="tar", lag=i)
th.tar[i+2] <- t3a$basic[,2]
}
th.tar

t4 <- ciTarThd(PREVGSP, PDISTGSP, model="mtar", lag=0); (th.mtar <- t4$basic)
plot(t4)
mttt<-t4$th.final
for (i in 1:12) {
t4a <- ciTarThd(PREVGSP,PDISTGSP, model="mtar", lag=i)
th.mtar[i+2] <- t4a$basic[,2]
}
th.mtar

t.tar <- ttt; t.mtar <- mttt
#t.tar <- -8.041; t.mtar <- -0.451 # lag = 0 to 4
#t.tar <- -8.701 ; t.mtar <- -0.451 # lag = 5 to 12

mx <- 12
(g1 <-ciTarLag(y=PREVGSP, x=PDISTGSP, model="tar", maxlag=mx, thresh= 0)); plot(g1)
(g2 <-ciTarLag(y=PREVGSP, x=PDISTGSP, model="mtar",maxlag=mx, thresh= 0)); plot(g2)
(g3 <-ciTarLag(y=PREVGSP, x=PDISTGSP, model="tar", maxlag=mx, thresh=t.tar)); plot(g3)
(g4 <-ciTarLag(y=PREVGSP, x=PDISTGSP, model="mtar",maxlag=mx, thresh=t.mtar)); plot(g4)


vv <- 0
(f1 <- ciTarFit(y=PREVGSP, x=PDISTGSP, model="tar", lag=vv, thresh=0 ))
(f2 <- ciTarFit(y=PREVGSP, x=PDISTGSP, model="tar", lag=vv, thresh=t.tar ))
(f3 <- ciTarFit(y=PREVGSP, x=PDISTGSP, model="mtar", lag=vv, thresh=0 ))
(f4 <- ciTarFit(y=PREVGSP, x=PDISTGSP, model="mtar", lag=vv, thresh=t.mtar))

r0 <- cbind(summary(f1)$dia, summary(f2)$dia, summary(f3)$dia,
summary(f4)$dia)
diag <- r0[c(1:4, 6:7, 12:14, 8, 9, 11), c(1,2,4,6,8)]
rownames(diag) <- 1:nrow(diag); diag
e1 <- summary(f1)$out; e2 <- summary(f2)$out
e3 <- summary(f3)$out; e4 <- summary(f4)$out; rbind(e1, e2, e3, e4)

ee <- list(e1, e2, e3, e4); vect <- NULL
for (i in 1:4) {
ef <- data.frame(ee[i])
vect2 <- c(paste(ef[3, "estimate"], ef[3, "sign"], sep=""),
paste("(", ef[3, "t.value"], ")", sep=""),
paste(ef[4, "estimate"], ef[4, "sign"], sep=""),
paste("(", ef[4, "t.value"], ")", sep=""))
vect <- cbind(vect, vect2)
}
item <- c("pos.coeff","pos.t.value", "neg.coeff","neg.t.value")
ve <- data.frame(cbind(item, vect)); colnames(ve) <- colnames(diag)
( res.CI <- rbind(diag, ve)[c(1:2, 13:16, 3:12), ] )
rownames(res.CI) <- 1:nrow(res.CI)

(sem <- ecmSymFit(y=PREVGSP, x=PDISTGSP, lag=1)); names(sem)
(ediaa <- ecmDiag(sem, 3))

aem <- ecmAsyFit(y=PREVGSP, x=PDISTGSP,lag=1, model="mtar", split=FALSE, thresh=t.mtar)
aem
(ccc <- summary(aem))

(edia <- ecmDiag(aem, 3))
(tes <- ecmAsyTest(aem)$out)



aemm <- ecmAsyFit(y=PREVGSP, x=PDISTGSP,lag=1, model="tar", split=FALSE, thresh=t.tar)
aemm
(ccc <- summary(aemm))


(edia <- ecmDiag(aemm, 3))
(tes <- ecmAsyTest(aemm)$out)


```





